apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: multi
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: multi
    tier: frontend
